# Generated by Django 4.1.1 on 2022-10-13 13:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('age', models.IntegerField(blank=True)),
                ('id', models.UUIDField(default=uuid.uuid3, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('title', models.CharField(blank=True, max_length=40)),
                ('date_released', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid3, editable=False, primary_key=True, serialize=False, unique=True)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('content', models.CharField(blank=True, max_length=5000)),
                ('id', models.UUIDField(default=uuid.uuid3, editable=False, primary_key=True, serialize=False, unique=True)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.song')),
            ],
        ),
    ]
