# Generated by Django 4.1.1 on 2022-10-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_alter_artist_id_alter_lyric_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
